# Start the containers

[tasks.require]
script = '''
#!/usr/bin/env bash
'''

[tasks.run]
dependencies = ["require"]
command = "docker"
args = ["compose", "up", "-d", "--build"]

[tasks.kill]
command = "docker"
args = ["compose", "kill"]

[tasks.restart]
dependencies = ["kill", "run"]

[tasks.bee]
script = '''
#!/bin/bash
set -eu
 docker compose exec --user user -it hive bash /opt/hive/bee.sh
'''

[tasks.root]
script = '''
#!/bin/bash
set -eu
docker compose exec -it hive /bin/bash
'''
[tasks.user]
script = '''
#!/bin/bash
set -eu
docker compose exec --user user -it hive /bin/bash
'''
